apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value1
spec:
  nodeSelector:
    label-key1: label-value1
  completions: 5
  parallelism: 2
  selector:
    matchLabels:
      label-key1: label-value1
  template:
    metadata:
      name: pod-name
      labels:
        label-keys: label-value1
    spec:
      restartPolicy: Never
      containers:
        - name: container-name
          image: image-name
          ports:
            - containerPort: 80
          readlinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSecons: 30
            failureThreshold: 0
            successThreshold: 0
