apiVersion: v1
kind: PersistentVolume
metadata:
  name: perrsistent-volume-name
spec:
  accessNodes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/location

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-name
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    request:
      storage: 1gi