apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-env-config
data:
  APPLICATIONA: My Cool Application
  VERSION; 1.0.0

--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-env
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-env
  template:
    metadata:
      name: nodejs-env
      labels:
        name: nodeje-env
    spec:
      contianers:
        - name: nodejs-env
          imae: khannedy/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-env-config
          env:
            - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: medatadata.namespace
            - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.podIP
            - name: POD_NODE
                valueFrom:  
                  fieldRef:
                    fieldPath: metadata.nodeName